### ISSUE TITLE
Clipboard won't get fixed by keyboard restart in Aaslakkajärvi

### ISSUE THREAD

**Issue by Mikaela** [sailfishos/sailfish-utilities#25]
Sometimes my clipboard stops taking anything new into it and gets stuck with the current paste. 

Previously this has been helped by restarting the keyboard which also says in the help text that it should be used if clipboard stops working, but now nothing happens when you press it other than the loading screen and "Restart keyboard: OK"

**Comment by kimmoli** [comment]
clipboard requires usually a lipstick restart.

**Comment by deztructor** [comment]
https://bugs.merproject.org/show_bug.cgi?id=1129

**Comment by deztructor** [comment]
And branch: https://github.com/sailfishos/sailfish-utilities/tree/mer1129-restart-ui
PR will follow soon.

**Comment by Mikaela** [comment]
There is just the issue that restarting lipstick closes all apps you have open.

**Comment by deztructor** [comment]
@Mikaela yes, it is. But lipstick restart could be considered as "fast" device restart, not as the way to fix clipboard.

**Comment by deztructor** [comment]
https://github.com/sailfishos/sailfish-utilities/pull/27

**Comment by Mikaela** [comment]
This has been here for so long time and I just now saw the wrong string again so I thought I could try fixing this by myself. https://github.com/sailfishos/sailfish-utilities/pull/31

**Comment by Mikaela** [comment]
This will be fixed by #33 and I am closing this, because we are apparently supposed to believe that this is  duplicate of MER#1129 (add support for restarting lipstick, not "wrong string in restart clipboard".
