### ISSUE TITLE
Restart msyncd button

### ISSUE THREAD

**Issue by tadzik** [sailfishos/sailfish-utilities#30]
I find msyncd hanging quite often, so I usually keep a terminal open to have `systemctl --user restart msyncd` in handy. It'd be nice to have a convenient button in settings gor it.

**Comment by deztructor** [comment]
Could you describe (or link to) the issue you are fixing by restarting msyncd?

**Comment by tadzik** [comment]
The issue I was fixing with it was tweets/emails not syncing for whatever reason.

**Comment by tadzik** [comment]
(Haven't had that problem for quite a while now, and have no need for the button. Closing).
