### ISSUE TITLE
Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by Mikaela** [sailfishos/sailfish-utilities#32]
I am random user trying to fix #25 and I was told that I am not following MER patch submission rules.

It would be helpful if there was CONTRIBUTING.md file as enouraged by GitHub and even without it it would be helpful if it was linked to in README.md or was findable with DuckDuckGo or Google.

I was also told that I must refer to MER bug in commit message, but I don't understand how do I do that when there never was a MER bug, but GitHub issue.

* https://github.com/blog/1184-contributing-guidelines
* https://github.com/sailfishos/sailfish-utilities/pull/31#issuecomment-139478316

**Comment by deztructor** [comment]
Good points

**Comment by deztructor** [comment]
https://github.com/sailfishos/sailfish-utilities/blob/master/CONTRIBUTING.org
