### ISSUE TITLE
Introduce Bluetooth service restart

### ISSUE THREAD

**Issue by Termitebug** [sailfishos/sailfish-utilities#61]
Many Sailfish OS releases has passed with some kind of Bluetooth issues of devices.
My view is that if you want to offer best user experience by now you should offer this feature as a temporary solution to underlying vendor adaptation bugs. Many non-technical end users are not patient enough, to wait for long term adaptation fix.
So please accept and implement @nephros Pull request to next OS release stop milestone.
Of course it would mean extra work of translation round, but it will benefit in a long-term developing.

**Comment by llewelld** [comment]
Thanks for raising this @Termitebug. We're taking another look at the PR, and hopefully we'll be able to integrate it.

**Comment by llewelld** [comment]
The PR for reference:

https://github.com/sailfishos/sailfish-utilities/pull/54
